language: android
android:
  components:
    - build-tools-25.0.2
    - android-18
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'